// <auto-generated />
namespace DatabaseActivities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PoundNewtons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PoundNewtons));
        
        string IMigrationMetadata.Id
        {
            get { return "201802281632009_PoundNewtons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
